# Generated by Django 3.2 on 2021-05-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0002_auto_20210505_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
