# Generated by Django 3.2 on 2021-05-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0021_alter_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('prescription', models.CharField(default='None', max_length=50, verbose_name='Prescription')),
                ('track_number', models.CharField(default='None', max_length=50, verbose_name='Tracking Number')),
                ('notes', models.CharField(default='None', max_length=50, verbose_name='Additional Notes')),
                ('appt', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.appointment')),
            ],
        ),
    ]
