# Generated by Django 3.2 on 2021-05-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_remove_appointment_prescription'),
        ('appointment', '0002_remove_prescription_appt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appt',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.appointment'),
        ),
    ]
