# Generated by Django 3.2 on 2021-05-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_remove_appointment_prescription'),
        ('appointment', '0003_prescription_appt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appt',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.CharField(default='None', max_length=50, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.CharField(default='None', max_length=50, null=True, verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='track_number',
            field=models.CharField(default='None', max_length=50, null=True, verbose_name='Tracking Number'),
        ),
    ]
