# Generated by Django 3.2 on 2021-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20210519_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='track_number',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Tracking Number'),
        ),
    ]
