# Generated by Django 3.2.3 on 2021-06-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20210519_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='meeting_id',
            field=models.CharField(default=None, max_length=48, null=True, unique=True, verbose_name='Meetind ID'),
        ),
    ]
