# Generated by Django 3.2.3 on 2021-06-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_prescription_meeting_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='meeting_id',
        ),
    ]
