# Generated by Django 3.2.3 on 2021-06-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_appointment_ms_event_created'),
        ('appointment', '0008_remove_prescription_meeting_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prescription',
            new_name='ApptDetails',
        ),
    ]
