# Generated by Django 3.2.4 on 2021-07-22 17:00

import appointment.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_remove_appointment_unique_id'),
        ('appointment', '0010_remove_apptdetails_track_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.UUID('82c09ccd-3070-4033-aa29-9c1d098488a5'), editable=False, unique=True)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to=appointment.models.get_upload_path)),
                ('appt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apptimage_appt', to='book.appointment')),
            ],
        ),
    ]
