# Generated by Django 3.2.4 on 2021-07-22 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_apptimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptimage',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('91300966-769e-4c3c-8bbe-5580e60ea5be'), editable=False, unique=True),
        ),
    ]
