# Generated by Django 3.2.4 on 2021-07-22 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_apptimage_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptimage',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c9a1d8b0-b538-4cfb-88c6-c72f52f098fa'), editable=False, unique=True),
        ),
    ]
