# Generated by Django 3.2.4 on 2021-07-22 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_apptimage_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptimage',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
