# Generated by Django 3.2.4 on 2021-08-03 14:44

import appointment.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_remove_appointment_unique_id'),
        ('appointment', '0014_alter_apptimage_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_file', models.FileField(upload_to=appointment.models.get_upload_path)),
                ('file_type', models.CharField(default='', max_length=10, null=True, verbose_name='File Extension Type')),
                ('appt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apptfile_appt', to='book.appointment')),
            ],
        ),
        migrations.DeleteModel(
            name='ApptImage',
        ),
    ]
