# Generated by Django 3.2.4 on 2021-08-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_auto_20210803_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptfile',
            name='content_type',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='File Content Type'),
        ),
    ]
