# Generated by Django 3.2.4 on 2021-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_apptfile_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptfile',
            name='friendly_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Original Uploaded Name'),
        ),
    ]
