# Generated by Django 3.2.4 on 2021-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_apptfile_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptfile',
            name='content_type',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='File Content Type'),
        ),
    ]
