# Generated by Django 3.2.4 on 2021-08-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_alter_apptfile_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptfile',
            name='content_type',
            field=models.CharField(default='', max_length=71, null=True, verbose_name='File Content Type'),
        ),
    ]
