# Generated by Django 3.2 on 2021-05-05 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='ohip_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length must be 13', regex='^{13}$')], verbose_name='OHIP Number'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='ohip_version_code',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length must be 2', regex='^{2}$')], verbose_name='OHIP Version Code'),
        ),
    ]
