# Generated by Django 3.2 on 2021-05-05 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210504_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length must be 13', regex='^{13}$')], verbose_name='User Phone Number'),
        ),
    ]
