# Generated by Django 3.2 on 2021-05-05 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210504_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='ohip_version_code',
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='ohip_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length must be 15', regex='^{15}$')], verbose_name='OHIP Number'),
        ),
    ]
