# Generated by Django 3.2 on 2021-05-05 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210504_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length must be 14', regex='^{14}$')], verbose_name='User Phone Number'),
        ),
    ]
