# Generated by Django 3.2 on 2021-05-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='access',
            field=models.CharField(default='None', max_length=50, verbose_name='Doctor Access Code'),
        ),
    ]
