# Generated by Django 3.2 on 2021-05-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_doctorinfo_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='certification',
        ),
    ]
