# Generated by Django 3.2 on 2021-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_doctorinfo_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='access',
            field=models.CharField(default='None', max_length=100, verbose_name='Doctor Access Code'),
        ),
    ]
