# Generated by Django 3.2 on 2021-05-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_doctorinfo_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='access',
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='certification',
            field=models.CharField(default='None', max_length=50, verbose_name='Doctor Identification Piece'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='languages',
            field=models.CharField(default='None', max_length=100, verbose_name="Doctor's Known Languages"),
        ),
    ]
