# Generated by Django 3.2 on 2021-05-05 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210505_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='ohip_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length must be 15', regex='^{15}$')], verbose_name='OHIP Number'),
        ),
    ]
