# Generated by Django 3.2 on 2021-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_patientinfo_ohip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='certification',
            field=models.CharField(default='None', max_length=50, verbose_name='Doctor Qualifications'),
        ),
    ]
