# Generated by Django 3.2.3 on 2021-05-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_doctorinfo_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='meeting_url',
            field=models.CharField(default=None, max_length=200, verbose_name="Doctor's Meeting Link"),
        ),
    ]
