# Generated by Django 3.2.3 on 2021-05-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_doctorinfo_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='ohip_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='OHIP Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='User Phone Number'),
        ),
    ]
