# Generated by Django 3.2.3 on 2021-05-25 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210525_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='meeting_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, unique=True, verbose_name="Doctor's Meeting Link"),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='ohip_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be in format XXXX-XXX-XXX-XX', regex='^.{15}$')], verbose_name='OHIP Number'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be in format XXX-XXX-XXXX', regex='^.{14}$')], verbose_name='User Phone Number'),
        ),
    ]
