# Generated by Django 3.2.3 on 2021-05-26 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210525_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Phone number must be 10 digits long', regex='^.{10}$')], verbose_name='User Phone Number'),
        ),
    ]
