# Generated by Django 3.2.3 on 2021-05-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='User Preferred Name'),
        ),
    ]
