# Generated by Django 3.2.3 on 2021-06-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='ms_authenticated',
            field=models.BooleanField(default=False, verbose_name='Connected to MS Account'),
        ),
    ]
