# Generated by Django 3.2.3 on 2021-06-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_doctorinfo_ms_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='meeting_url',
        ),
    ]
