# Generated by Django 3.2.3 on 2021-06-11 16:50

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210610_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('email__isnull', True), ('phone__isnull', False)), models.Q(('email__isnull', False), ('phone__isnull', True)), _connector='OR'), name='accounts_user_email_or_phone'),
        ),
    ]
