# Generated by Django 3.2.3 on 2021-06-11 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_user_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_email_or_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator('Please enter a valid e-mail')], verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Phone number must be 10 digits long', regex='^.{10}$')], verbose_name='User Phone Number'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('email__isnull', True), ('phone__isnull', False)), models.Q(('email__isnull', False), ('phone__isnull', True)), models.Q(('email__isnull', False), ('phone__isnull', False)), _connector='OR'), name='accounts_user_email_or_phone'),
        ),
    ]
