# Generated by Django 3.2.3 on 2021-06-11 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210611_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator('Please enter a valid e-mail')], verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Phone number must be 10 digits long', regex='^.{10}$')], verbose_name='User Phone Number'),
        ),
    ]
