# Generated by Django 3.2.4 on 2021-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20210624_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=True, verbose_name='SMS Notifications'),
        ),
    ]
