# Generated by Django 3.2.4 on 2021-06-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20210625_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='address_coords',
            field=models.CharField(default=None, max_length=25, verbose_name='User Address (lat,long)'),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='full_address',
            field=models.CharField(default=None, max_length=100, verbose_name='User Address'),
        ),
    ]
