# Generated by Django 3.2.4 on 2021-06-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20210628_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='address_coords',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='User Address (lat,long)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='full_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='User Address'),
        ),
    ]
