# Generated by Django 3.2.4 on 2021-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210628_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='full_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=7, null=True, verbose_name='User Postal Code'),
        ),
    ]
