# Generated by Django 3.2.4 on 2021-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210628_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='address_coords',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='User Address (lat,long)'),
        ),
    ]
