# Generated by Django 3.2.4 on 2021-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_patientinfo_address_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='pharmacy',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='User Preferred Pharmacy'),
        ),
    ]
