# Generated by Django 3.2.4 on 2021-07-05 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_patientinfo_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Phone number must be 10 digits long', regex='^.{10}$')], verbose_name='User Phone Number'),
        ),
    ]
