# Generated by Django 3.2.4 on 2021-07-14 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
