# Generated by Django 3.2.4 on 2021-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20210714_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Office Location'),
        ),
    ]
