# Generated by Django 3.2.4 on 2021-07-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_doctorinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_new_email',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Possible New Email'),
        ),
    ]
