# Generated by Django 3.2 on 2021-05-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_patientinfo_ohip_number'),
        ('book', '0002_auto_20210505_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='accounts.patient'),
        ),
    ]
