# Generated by Django 3.2 on 2021-05-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
