# Generated by Django 3.2 on 2021-05-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210507_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[('800AM', '8:00AM'), ('815AM', '8:15AM'), ('830AM', '8:30AM'), ('845AM', '8:45AM'), ('900AM', '9:00AM'), ('915AM', '9:15AM'), ('930AM', '9:30AM'), ('945AM', '9:45AM'), ('1000AM', '10:00AM'), ('1015AM', '10:15AM'), ('1030AM', '10:30AM'), ('1045AM', '10:45AM'), ('1100AM', '11:00AM'), ('1115AM', '11:15AM'), ('1130AM', '11:30AM'), ('1145AM', '11:45AM'), ('1200PM', '12:00PM'), ('1215PM', '12:15PM'), ('1230PM', '12:30PM'), ('1245PM', '12:45PM'), ('100PM', '1:00PM'), ('115PM', '1:15PM'), ('130PM', '1:30PM'), ('145PM', '1:45PM'), ('200PM', '2:00PM'), ('215PM', '2:15PM'), ('230PM', '2:30PM'), ('245PM', '2:45PM'), ('300PM', '3:00PM'), ('315PM', '3:15PM'), ('330PM', '3:30PM'), ('345PM', '3:45PM'), ('400PM', '4:00PM'), ('415PM', '4:15PM'), ('430PM', '4:30PM'), ('445PM', '4:45PM'), ('500PM', '5:00PM'), ('515PM', '5:15PM'), ('530PM', '5:30PM'), ('545PM', '5:45PM'), ('600PM', '6:00PM'), ('615PM', '6:15PM'), ('630PM', '6:30PM'), ('645PM', '6:45PM'), ('700PM', '7:00PM'), ('715PM', '7:15PM'), ('730PM', '7:30PM'), ('745PM', '7:45PM')], default=None),
        ),
    ]
