# Generated by Django 3.2 on 2021-05-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_patientinfo_ohip_number'),
        ('book', '0011_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('8:00AM', '8:00AM'), ('8:15AM', '8:15AM'), ('8:30AM', '8:30AM'), ('8:45AM', '8:45AM'), ('9:00AM', '9:00AM'), ('9:15AM', '9:15AM'), ('9:30AM', '9:30AM'), ('9:45AM', '9:45AM'), ('10:00AM', '10:00AM'), ('10:15AM', '10:15AM'), ('10:30AM', '10:30AM'), ('10:45AM', '10:45AM'), ('11:00AM', '11:00AM'), ('11:15AM', '11:15AM'), ('11:30AM', '11:30AM'), ('11:45AM', '11:45AM'), ('12:00PM', '12:00PM'), ('12:15PM', '12:15PM'), ('12:30PM', '12:30PM'), ('12:45PM', '12:45PM'), ('1:00PM', '1:00PM'), ('1:15PM', '1:15PM'), ('1:30PM', '1:30PM'), ('1:45PM', '1:45PM'), ('2:00PM', '2:00PM'), ('2:15PM', '2:15PM'), ('2:30PM', '2:30PM'), ('2:45PM', '2:45PM'), ('3:00PM', '3:00PM'), ('3:15PM', '3:15PM'), ('3:30PM', '3:30PM'), ('3:45PM', '3:45PM'), ('4:00PM', '4:00PM'), ('4:15PM', '4:15PM'), ('4:30PM', '4:30PM'), ('4:45PM', '4:45PM'), ('5:00PM', '5:00PM'), ('5:15PM', '5:15PM'), ('5:30PM', '5:30PM'), ('5:45PM', '5:45PM'), ('6:00PM', '6:00PM'), ('6:15PM', '6:15PM'), ('6:30PM', '6:30PM'), ('6:45PM', '6:45PM'), ('7:00PM', '7:00PM'), ('7:15PM', '7:15PM'), ('7:30PM', '7:30PM'), ('7:45PM', '7:45PM')], default=None, max_length=7),
        ),
    ]
