# Generated by Django 3.2 on 2021-05-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_patientinfo_ohip_number'),
        ('book', '0012_auto_20210507_2030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'doctor')},
        ),
    ]
