# Generated by Django 3.2 on 2021-05-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('800', '8:00AM'), ('815', '8:15AM'), ('830', '8:30AM'), ('845', '8:45AM'), ('900', '9:00AM'), ('915', '9:15AM'), ('930', '9:30AM'), ('945', '9:45AM'), ('A00', '10:00AM'), ('A15', '10:15AM'), ('A30', '10:30AM'), ('A45', '10:45AM'), ('B00', '11:00AM'), ('B15', '11:15AM'), ('B30', '11:30AM'), ('B45', '11:45AM'), ('C00', '12:00PM'), ('C15', '12:15PM'), ('C30', '12:30PM'), ('C45', '12:45PM'), ('D00', '1:00PM'), ('D15', '1:15PM'), ('D30', '1:30PM'), ('D45', '1:45PM'), ('E00', '2:00PM'), ('E15', '2:15PM'), ('E30', '2:30PM'), ('E45', '2:45PM'), ('F00', '3:00PM'), ('F15', '3:15PM'), ('F30', '3:30PM'), ('F45', '3:45PM'), ('G00', '4:00PM'), ('G15', '4:15PM'), ('G30', '4:30PM'), ('G45', '4:45PM'), ('H00', '5:00PM'), ('H15', '5:15PM'), ('H30', '5:30PM'), ('H45', '5:45PM'), ('I00', '6:00PM'), ('I15', '6:15PM'), ('I30', '6:30PM'), ('I45', '6:45PM'), ('J00', '7:00PM'), ('J15', '7:15PM'), ('J30', '7:30PM'), ('J45', '7:45PM')], default=None, max_length=3),
        ),
    ]
