# Generated by Django 3.2.3 on 2021-06-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_remove_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_id',
            field=models.CharField(default=None, max_length=48, null=True, unique=True),
        ),
    ]
