# Generated by Django 3.2.3 on 2021-06-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ms_event_created',
            field=models.BooleanField(default=False),
        ),
    ]
