# Generated by Django 3.2.4 on 2021-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_appointment_ms_event_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='unique_id',
            field=models.UUIDField(default=None, unique=True),
        ),
    ]
