# Generated by Django 3.2.4 on 2021-08-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_alter_appointment_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent2',
            field=models.IntegerField(choices=[(0, 'No Reminder'), (1, 'One Day Reminder'), (2, '15 Minute Reminder')], default=0),
        ),
    ]
