# Generated by Django 3.2.4 on 2021-08-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_appointment_reminder_sent2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_sent',
        ),
    ]
