# Generated by Django 3.2.4 on 2021-08-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_remove_appointment_reminder_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='reminder_sent2',
            new_name='reminder_sent',
        ),
    ]
